JOKES = [
    "I asked a pigeon for directions, but it only knew the scenic coo-t.",
    "The pigeon opened a bakery because it was already great with crumbs.",
    "A pigeon joined the orchestra and only played the coo-kulele.",
    "The pigeon skipped school because it was too coo for class.",
    "I hired a pigeon accountant; it kept balancing the bread crumbs.",
    "A pigeon became a detective because every clue left a trail of crumbs.",
    "The pigeon hated elevators, so it took the stair-flap.",
    "A pigeon wrote a novel, but every chapter had a cliff-roost.",
    "The pigeon got promoted because it always rose above the flock.",
    "A pigeon started a podcast called Coo and Tell.",
    "The pigeon brought a suitcase because it was going on a wing trip.",
    "A pigeon never lies; it just coos the truth softly.",
    "The pigeon bought sneakers for its daily sidewalk strut.",
    "A pigeon became a chef and specialized in crumb brulee.",
    "The pigeon refused drama; it preferred peace, quiet, and bagels.",
    "A pigeon joined the gym for better flap definition.",
    "The pigeon studied philosophy and asked, to coo or not to coo?",
    "A pigeon became a banker because it understood nest eggs.",
    "The pigeon opened a salon for feather maintenance.",
    "A pigeon ran for mayor on a strong pro-breadcrumb platform.",
    "The pigeon hated secrets because news travels fast in a flock.",
    "A pigeon joined a band but kept stealing the spotlight and the snacks.",
    "The pigeon became a teacher and gave pop coo-izzes.",
    "A pigeon went camping and called it a roost retreat.",
    "The pigeon brought an umbrella in case of scattered showers and crackers.",
    "A pigeon got a library card to check out books on wing theory.",
    "The pigeon loved math because it could count on its flock.",
    "A pigeon became a poet and wrote only coo-plets.",
    "The pigeon opened a cafe where every table came with crumbs.",
    "A pigeon took acting lessons to improve its dramatic head bob.",
    "The pigeon joined tech support because it knew how to reboot a coo-ter.",
    "A pigeon became a pilot, then complained there was too much flying.",
    "The pigeon refused fast food unless it fell on the pavement first.",
    "A pigeon started yoga to perfect the downward dove.",
    "The pigeon got a watch because it was tired of winging the time.",
    "A pigeon joined a choir and kept cooing over everyone.",
    "The pigeon became a gardener and planted seed money.",
    "A pigeon opened a shoe store for birds with serious street style.",
    "The pigeon did stand-up, but every joke landed on a statue.",
    "A pigeon became a historian to study ancient roosts.",
    "The pigeon took a cooking class and aced the bread unit.",
    "A pigeon became a painter and specialized in rooftop landscapes.",
    "The pigeon joined a debate club and made several fair coo-nterpoints.",
    "A pigeon got into real estate because every ledge was prime property.",
    "The pigeon became a tailor and made custom feather jackets.",
    "A pigeon joined a book club but only read fly-on-the-wall memoirs.",
    "The pigeon disliked online meetings because nobody passed snacks.",
    "A pigeon got a job in security because it was always watching the square.",
    "The pigeon became a magician and made a whole sandwich disappear.",
    "A pigeon started a newspaper called The Daily Coo.",
    "The pigeon bought a map and still followed the smell of bread.",
    "A pigeon became a lifeguard but only saved soggy fries.",
    "The pigeon tried meditation and reached inner peas.",
    "A pigeon joined a chess club and always protected the rook.",
    "The pigeon became a tailor because every outfit needed a little flair.",
    "A pigeon went to court and pleaded not guilty by reason of crumbs.",
    "The pigeon started a delivery service but kept stopping for lunch.",
    "A pigeon joined a dance crew and mastered the sidewalk shuffle.",
    "The pigeon became a dentist for beak-to-beak referrals.",
    "A pigeon moved to the city for better crumb opportunities.",
    "The pigeon became a critic and gave every bakery five coos.",
    "A pigeon took up photography and focused on candid crumbs.",
    "The pigeon joined a startup and pitched cloud-based roosting.",
    "A pigeon became a comedian because it had impeccable timing and terrible parking.",
    "The pigeon got a diary but everyone in the flock read it anyway.",
    "A pigeon opened a hotel where checkout was at first flap.",
    "The pigeon became a lawyer and objected to seedless bread.",
    "A pigeon joined a museum tour and admired the statues professionally.",
    "The pigeon started a savings plan: one crumb today, two crumbs tomorrow.",
    "A pigeon became a weather reporter because it was always under the sky.",
    "The pigeon tried to whisper, but it came out as breaking coos.",
    "A pigeon became a barber and offered feather trims.",
    "The pigeon entered a race and won by a beak.",
    "A pigeon started a gym class called Flap Fit.",
    "The pigeon became a chef and invented pavement parmesan.",
    "A pigeon went to therapy to discuss its fear of empty plazas.",
    "The pigeon became an architect and designed luxury nests.",
    "A pigeon joined a choir and insisted every song needed more coo.",
    "The pigeon became a librarian and shushed people with a wing.",
    "A pigeon opened a repair shop for broken birdhouses.",
    "The pigeon bought sunglasses because the future looked bright and crumbly.",
    "A pigeon became a scientist and studied the physics of falling fries.",
    "The pigeon tried minimalism, but kept one emergency bagel.",
    "A pigeon joined a cooking show and got eliminated for stealing ingredients.",
    "The pigeon became a motivational speaker: believe in your shelf.",
    "A pigeon joined a circus as the amazing flying lunch thief.",
    "The pigeon became a banker and offered low-interest nest loans.",
    "A pigeon took a vacation but still checked every sidewalk for snacks.",
    "The pigeon became a tailor and said every suit needed wing room.",
    "A pigeon opened a school for advanced strutting.",
    "The pigeon became a musician and only performed unplugged coo-stic sets.",
    "A pigeon joined a treasure hunt and found half a pretzel.",
    "The pigeon became a referee and called fowl every five minutes.",
    "A pigeon opened a spa with premium dust baths.",
    "The pigeon became a coach and told everyone to flap through adversity.",
    "A pigeon joined a mystery club and solved the case of the missing muffin.",
    "The pigeon became a judge and ruled in favor of more bread.",
    "A pigeon started a fashion line called Street Feathers.",
    "The pigeon became a sailor but complained there were no sidewalks at sea.",
    "A pigeon took a painting class and only used sky blue and crumb brown.",
    "The pigeon became a dentist and specialized in beak care.",
    "A pigeon joined a film crew as the aerial camera department.",
    "The pigeon started a bakery review blog called Crumb and Get It.",
    "A pigeon became a professor of applied coo-nomics.",
    "The pigeon became a plumber because every fountain had potential.",
    "A pigeon joined a choir but kept improvising snack breaks.",
    "The pigeon became a tour guide and pointed out every bakery within range.",
    "A pigeon got into politics and promised crumbs for all.",
    "The pigeon became a locksmith because every coop needs a key.",
    "A pigeon joined a rock band and named it The Rolling Scones.",
    "The pigeon became a clockmaker because timing is everything in snack raids.",
    "A pigeon started a newsletter for serious ledge investors.",
    "The pigeon became a florist and arranged seed bouquets.",
    "A pigeon joined a theater troupe and nailed the dramatic flap.",
    "The pigeon became a cartographer and mapped every bench in town.",
    "A pigeon opened a diner where the special was whatever you dropped.",
    "The pigeon became a philosopher and questioned free bird will.",
    "A pigeon joined a cleaning crew but only cleared the crumbs.",
    "The pigeon became a knight and defended the round table scraps.",
    "A pigeon took up fencing but preferred sitting on the fence.",
    "The pigeon became a wizard and cast the spell crumbus maximus.",
]
